/* ============================================================
   ARUTA.SH — CONFIG
   Modifica questo file per aggiornare contenuti, social e testi.
   ============================================================ */

/* ════════════════════════════
   TRANSLATIONS
════════════════════════════ */
const i18n = {
    it: {
        char_class: 'Streamer · Programmatore · Avventuriero',
        sec_home:   'Home',
        sec_about:  'About',
        sec_live:   'Live',
        sec_links:  'Link',
        live_title: 'Reame Live',
        live_desc: 'Osserva il mago in azione attraverso il portale',
        live_offline: 'Il mago non \u00e8 nel reame... segui per essere avvisato del prossimo rituale.',
        links_desc: 'Trovami su queste piattaforme',
        bio: 'Mi chiamo Stefano Aruta. Programmatore appassionato con un amore profondo per anime, manga, Ultima Online, Minecraft e D&D. Come i protagonisti delle storie isekai, mi lancio ora in un nuovo viaggio: lo streaming. Cercando mondi senza confini dove libertà e creatività non hanno limite.',
        boot: [
            '✦ Un\'anima si risveglia in questo reame...',
            '⊕ Consultando il Tomo Antico...',
            '⋆ I Quattro Elementi rispondono...',
            '✦ Il cerchio magico prende forma...',
            '⊕ Il portale si apre...',
            '✦ Benvenuto nel Reame di Aruta ✦'
        ],
        int_gaming:    'Gaming',
        int_anime:     'Anime & Manga',
        int_coding:    'Programmazione',
        int_streaming: 'Streaming',
        int_fantasy:   'Fantasy & GdR',
        int_openworld: 'Open World',
        projects_title: 'Progetti in Corso',
        proj_stars: 'stelle',
        proj_forks: 'fork',
        proj_commits: 'commit',
        proj_issues: 'issue',
        proj_created: 'Creato',
        proj_updated: 'Aggiornato',
        proj_loading: 'Consultando gli archivi...',
        proj_error: 'Pergamena non trovata',
        live_schedule_title: '✦ Prossimi Rituali ✦',
        live_day_tue: 'Martedì',
        live_day_thu: 'Giovedì',
        live_day_sat: 'Sabato',
        live_countdown: 'Prossimo rituale tra',
        discord_title: 'Gilda Arcana',
        clips_title: 'Momenti Epici',
        sec_settings: 'Impostazioni',
        settings_appearance: 'Aspetto',
        settings_theme: 'Tema',
        settings_theme_desc: 'Passa dalla modalità chiara a quella scura',
        settings_fontsize: 'Dimensione testo',
        settings_fontsize_desc: 'Regola la dimensione del testo',
        settings_font: 'Carattere',
        settings_font_desc: 'Famiglia di caratteri usata nel sito',
        settings_accent: 'Colore accento',
        settings_accent_desc: 'Scegli il colore principale',
        settings_clock: 'Orologio',
        settings_showdate: 'Mostra data',
        settings_showdate_desc: 'Mostra la data nella barra',
        settings_24h: 'Formato 24h',
        settings_24h_desc: 'Usa il formato a 24 ore',
        settings_sound: 'Suono',
        settings_ambient: 'Suono ambientale',
        settings_ambient_desc: 'Drone mistico di sottofondo',
        settings_language: 'Lingua',
        settings_lang: 'Lingua',
        settings_lang_desc: 'Seleziona la tua lingua',
        settings_about: 'Informazioni',
        settings_reset: 'Ripristina predefiniti',
        settings_reset_desc: 'Reimposta tutte le impostazioni ai valori predefiniti',
        settings_wipe: 'Cancella dati locali',
        settings_wipe_desc: 'Elimina tutti i dati salvati localmente e ricarica la pagina',
        settings_wipe_confirm: 'Cancellare tutti i dati locali e ricaricare la pagina?',
        toast_reset_done: 'Impostazioni ripristinate',
        toast_wipe_done: 'Dati locali cancellati. Ricarico…',
        confirm_wipe: 'Cancella',
        confirm_cancel: 'Annulla',
        start_share: 'Condividi',
        settings_performance: 'Prestazioni',
        settings_particles: 'Particelle',
        settings_particles_desc: 'Effetti particellari runici',
        settings_fog: 'Nebbia',
        settings_fog_desc: 'Strati di nebbia ambientale',
        settings_parallax: 'Parallasse',
        settings_parallax_desc: 'Effetto parallasse del mouse',
        settings_cursor: 'Cursore magico',
        settings_cursor_desc: 'Cursore personalizzato',
        settings_clickspells: 'Incantesimi click',
        settings_clickspells_desc: 'Esplosione runica al click',
        settings_circles: 'Cerchi magici',
        settings_circles_desc: 'Animazioni degli anelli rotanti',
        sec_terminal: 'Terminale',
        settings_permissions: 'Permessi',
        settings_widgets: 'Widget',
        settings_widgets_desc: 'Mini pannelli fluttuanti da pacchetti installati. I widget abilitati restano fissati sulla scrivania.',
        widgets_empty: 'Nessun widget disponibile. Installa un pacchetto che ne fornisce uno.',
        widgets_mobile_disabled: 'I widget sono nascosti sugli schermi mobili.',
        widget_uninstall_warning: 'Widget disattivato prima della disinstallazione',
        settings_install_pkg: 'Installa pacchetto',
        settings_install_pkg_desc: 'Importa un .zip con manifest.json + index.js',
        install_install: 'Installa',
        install_update: 'Aggiorna',
        install_title: 'Installare {name}?',
        install_update_title: 'Aggiornare {name}?',
        install_body: 'Tipo: {type}\nID: {id}\nVersione: {version}\nAutore: {author}\n\nPermessi dichiarati:\n{perms}',
        install_no_perms: '(nessuno)',
        install_installed: '{name} installato',
        install_updated: '{name} aggiornato',
        install_err_not_zip: 'Il file deve essere uno .zip',
        install_err_invalid: 'Manifest non valido',
        install_drop_label: 'Rilascia uno .zip per installare',
        term_welcome: '✦ Terminale Aruta — digita "help" per i comandi',
        term_help_header: 'Comandi integrati:',
        term_help_custom: 'Comandi installati:',
        term_unknown: 'comando sconosciuto:',
        perm_request_title: '{name} vuole accedere a {perm}',
        perm_deny: 'Nega',
        perm_allow_once: 'Consenti',
        perm_allow_always: 'Sempre',
        perm_grant: 'Concedi',
        perm_revoke: 'Revoca',
        perm_uninstall: 'Disinstalla',
        perm_uninstall_confirm: 'Disinstallare {name}?',
        perm_uninstalled: '{name} disinstallato',
        perm_empty: 'Nessun pacchetto installato.',
        perm_no_perms: 'Nessun permesso usato.',
        perm_state_granted: 'concesso',
        perm_state_denied: 'negato',
        perm_state_ask: 'da chiedere',
        perm_storage: 'storage locale',
        perm_storage_desc: 'Salvare e leggere dati persistenti propri dell\u2019app.',
        perm_notifications: 'notifiche',
        perm_notifications_desc: 'Mostrare toast nell\u2019interfaccia.',
        perm_windows: 'finestre',
        perm_windows_desc: 'Aprire o chiudere altre finestre del sistema.',
        perm_terminal: 'terminale',
        perm_terminal_desc: 'Stampare testo nel terminale.',
        perm_fetch: 'rete',
        perm_fetch_desc: 'Eseguire richieste HTTP a domini esterni.',
        perm_theme: 'tema',
        perm_theme_desc: 'Leggere e cambiare il tema (chiaro/scuro).',
        perm_clipboard: 'appunti',
        perm_clipboard_desc: 'Leggere o scrivere negli appunti del sistema.',
        perm_install: 'installa',
        perm_install_desc: 'Inviare un pacchetto .zip all\'installer. La conferma finale resta sempre con te.',
        cat_info: 'Informazioni',
        cat_games: 'Giochi',
        cat_tools: 'Strumenti',
        cat_creativity: 'Creatività',
        cat_other: 'Altro',
        cat_system: 'Sistema',
        settings_wipe_settings: 'Cancella solo impostazioni',
        settings_wipe_settings_desc: 'Azzera le preferenze ma conserva app, comandi e permessi',
        settings_wipe_settings_confirm: 'Azzerare le preferenze? App, comandi e relativi permessi saranno conservati.',
        toast_wipe_settings_done: 'Impostazioni azzerate. Ricarico…',
        settings_theme_follow: 'Segui tema di sistema',
        settings_theme_follow_desc: 'Adatta automaticamente chiaro/scuro al tuo SO',
        settings_bg: 'Sfondo',
        settings_bg_desc: 'Immagine o video personalizzato (salvato nel profilo)',
        settings_bg_pick: 'Carica…',
        settings_bg_clear: 'Rimuovi',
        settings_portrait: 'Ritratto',
        settings_portrait_desc: 'Sostituisci l\'immagine dell\'eroe',
        settings_portrait_pick: 'Carica…',
        settings_portrait_clear: 'Ripristina',
        settings_name: 'Nome visualizzato',
        settings_name_desc: 'Mostrato nella home e nel menu avvio',
        settings_name_clear: 'Ripristina',
        settings_profile: 'Profilo',
        settings_profile_status: 'Stato',
        settings_profile_not_linked: 'Non collegato',
        settings_profile_folder: 'Cartella collegata',
        settings_profile_folder_desc: 'Sincronizza impostazioni, app e dati in una cartella locale (solo Chromium).',
        settings_profile_pick: 'Scegli cartella…',
        settings_profile_reconnect: 'Riconnetti',
        settings_profile_unlink: 'Scollega',
        settings_profile_export: 'Esporta .zip',
        settings_profile_export_desc: 'Scarica un\'istantanea del profilo attuale.',
        settings_profile_export_btn: 'Esporta',
        settings_profile_import: 'Importa .zip',
        settings_profile_import_desc: 'Carica un profilo esportato (sostituisce lo stato attuale).',
        settings_profile_import_btn: 'Importa',
        settings_profile_help: 'Copia la cartella o lo .zip tra dispositivi per trasferire impostazioni, app e dati.',
        settings_status_default: 'Predefinito',
        win_minimize: 'Minimizza',
        win_maximize: 'Massimizza',
        win_close: 'Chiudi',
        start_btn: 'Avvio',
        start_btn_aria: 'Menu avvio',
        start_subtitle: 'Tomo del Mago Errante',
        sysinfo_title: 'Informazioni di sistema',
        sysinfo_btn: 'Info sistema',
        sysinfo_loading: 'Caricamento...',
        accent_gold: 'Oro',
        accent_purple: 'Viola',
        accent_cyan: 'Ciano',
        accent_rose: 'Rosa',
        accent_emerald: 'Smeraldo',
        accent_custom: 'Personalizzato',
        font_default: 'Arcano (Cinzel + Inter)',
        font_medieval: 'Medievale (IM Fell)',
        font_modern: 'Moderno Sans',
        font_serif: 'Serif Classico',
        font_mono: 'Monospace',
        font_nordic: 'Nordico (solo Cinzel)',
        settings_reset_btn: 'Ripristina',
        settings_wipe_settings_btn: 'Azzera',
        settings_wipe_all_btn: 'Cancella tutto'
    },
    en: {
        char_class: 'Streamer · Programmer · Adventurer',
        sec_home:   'Home',
        sec_about:  'About',
        sec_live:   'Live',
        sec_links:  'Links',
        live_title: 'Live Realm',
        live_desc: 'Watch the mage in action through the portal',
        live_offline: 'The mage is not in the realm... follow to be notified of the next ritual.',
        links_desc: 'Find me on these platforms',
        bio: 'My name is Stefano Aruta. A passionate programmer with a deep love for anime, manga, Ultima Online, Minecraft and D&D. Like the heroes of isekai tales, I now embark on a new journey: streaming. Seeking worlds without boundaries, where freedom and creativity know no limits.',
        boot: [
            '✦ A soul awakens in this realm...',
            '⊕ Consulting the Ancient Tome...',
            '⋆ The Four Elements respond...',
            '✦ The magic circle takes shape...',
            '⊕ The portal opens...',
            '✦ Welcome to the Realm of Aruta ✦'
        ],
        int_gaming:    'Gaming',
        int_anime:     'Anime & Manga',
        int_coding:    'Programming',
        int_streaming: 'Streaming',
        int_fantasy:   'Fantasy & RPG',
        int_openworld: 'Open World',
        projects_title: 'Current Projects',
        proj_stars: 'stars',
        proj_forks: 'forks',
        proj_commits: 'commits',
        proj_issues: 'issues',
        proj_created: 'Created',
        proj_updated: 'Updated',
        proj_loading: 'Consulting the archives...',
        proj_error: 'Scroll not found',
        live_schedule_title: '✦ Upcoming Rituals ✦',
        live_day_tue: 'Tuesday',
        live_day_thu: 'Thursday',
        live_day_sat: 'Saturday',
        live_countdown: 'Next ritual in',
        discord_title: 'Arcane Guild',
        clips_title: 'Epic Moments',
        sec_settings: 'Settings',
        settings_appearance: 'Appearance',
        settings_theme: 'Theme',
        settings_theme_desc: 'Switch between dark and light mode',
        settings_fontsize: 'Font Size',
        settings_fontsize_desc: 'Adjust text size',
        settings_font: 'Font Family',
        settings_font_desc: 'Typeface used across the site',
        settings_accent: 'Accent Color',
        settings_accent_desc: 'Choose your accent color',
        settings_clock: 'Clock',
        settings_showdate: 'Show Date',
        settings_showdate_desc: 'Display date in taskbar',
        settings_24h: '24h Format',
        settings_24h_desc: 'Use 24-hour time format',
        settings_sound: 'Sound',
        settings_ambient: 'Ambient Sound',
        settings_ambient_desc: 'Mystical background drone',
        settings_language: 'Language',
        settings_lang: 'Language',
        settings_lang_desc: 'Select your language',
        settings_about: 'About',
        settings_reset: 'Reset to Defaults',
        settings_reset_desc: 'Reset all settings to default values',
        settings_wipe: 'Wipe Local Data',
        settings_wipe_desc: 'Delete all locally stored data and reload the page',
        settings_wipe_confirm: 'Delete all locally stored data and reload the page?',
        toast_reset_done: 'Settings restored to defaults',
        toast_wipe_done: 'Local data wiped. Reloading…',
        confirm_wipe: 'Wipe',
        confirm_cancel: 'Cancel',
        start_share: 'Share',
        settings_performance: 'Performance',
        settings_particles: 'Particles',
        settings_particles_desc: 'Rune particle effects',
        settings_fog: 'Fog',
        settings_fog_desc: 'Ambient fog layers',
        settings_parallax: 'Parallax',
        settings_parallax_desc: 'Mouse parallax effect',
        settings_cursor: 'Magic Cursor',
        settings_cursor_desc: 'Custom cursor effect',
        settings_clickspells: 'Click Spells',
        settings_clickspells_desc: 'Rune burst on click',
        settings_circles: 'Magic Circles',
        settings_circles_desc: 'Rotating ring animations',
        sec_terminal: 'Terminal',
        settings_permissions: 'Permissions',
        settings_widgets: 'Widgets',
        settings_widgets_desc: 'Floating mini-panels from installed packages. Enabled widgets stay pinned on the desktop.',
        widgets_empty: 'No widgets available. Install a package that provides one.',
        widgets_mobile_disabled: 'Widgets are hidden on mobile screens.',
        widget_uninstall_warning: 'Widget disabled before uninstall',
        settings_install_pkg: 'Install package',
        settings_install_pkg_desc: 'Import a .zip with manifest.json + index.js',
        install_install: 'Install',
        install_update: 'Update',
        install_title: 'Install {name}?',
        install_update_title: 'Update {name}?',
        install_body: 'Type: {type}\nID: {id}\nVersion: {version}\nAuthor: {author}\n\nDeclared permissions:\n{perms}',
        install_no_perms: '(none)',
        install_installed: '{name} installed',
        install_updated: '{name} updated',
        install_err_not_zip: 'File must be a .zip',
        install_err_invalid: 'Invalid manifest',
        install_drop_label: 'Drop a .zip to install',
        term_welcome: '✦ Aruta Terminal — type "help" for commands',
        term_help_header: 'Built-in commands:',
        term_help_custom: 'Installed commands:',
        term_unknown: 'unknown command:',
        perm_request_title: '{name} wants to access {perm}',
        perm_deny: 'Deny',
        perm_allow_once: 'Allow',
        perm_allow_always: 'Always',
        perm_grant: 'Grant',
        perm_revoke: 'Revoke',
        perm_uninstall: 'Uninstall',
        perm_uninstall_confirm: 'Uninstall {name}?',
        perm_uninstalled: '{name} uninstalled',
        perm_empty: 'No packages installed.',
        perm_no_perms: 'No permissions used.',
        perm_state_granted: 'granted',
        perm_state_denied: 'denied',
        perm_state_ask: 'ask',
        perm_storage: 'local storage',
        perm_storage_desc: 'Save and read its own persistent data.',
        perm_notifications: 'notifications',
        perm_notifications_desc: 'Show toasts in the UI.',
        perm_windows: 'windows',
        perm_windows_desc: 'Open or close other system windows.',
        perm_terminal: 'terminal',
        perm_terminal_desc: 'Print text to the terminal.',
        perm_fetch: 'network',
        perm_fetch_desc: 'Make HTTP requests to external domains.',
        perm_theme: 'theme',
        perm_theme_desc: 'Read and change the (light/dark) theme.',
        perm_clipboard: 'clipboard',
        perm_clipboard_desc: 'Read or write the system clipboard.',
        perm_install: 'install',
        perm_install_desc: 'Submit a .zip package to the installer. You still confirm every install.',
        cat_info: 'Info',
        cat_games: 'Games',
        cat_tools: 'Tools',
        cat_creativity: 'Creativity',
        cat_other: 'Other',
        cat_system: 'System',
        settings_wipe_settings: 'Wipe Settings Only',
        settings_wipe_settings_desc: 'Reset preferences but keep installed apps, commands and permissions',
        settings_wipe_settings_confirm: 'Reset preferences? Installed apps, commands and their permissions will be kept.',
        toast_wipe_settings_done: 'Settings wiped. Reloading…',
        settings_theme_follow: 'Follow system theme',
        settings_theme_follow_desc: 'Match your OS dark/light preference automatically',
        settings_bg: 'Background',
        settings_bg_desc: 'Custom image or video loop (saved in your profile)',
        settings_bg_pick: 'Upload…',
        settings_bg_clear: 'Clear',
        settings_portrait: 'Portrait',
        settings_portrait_desc: 'Replace the hero portrait image',
        settings_portrait_pick: 'Upload…',
        settings_portrait_clear: 'Reset',
        settings_name: 'Display name',
        settings_name_desc: 'Shown in hero and start menu',
        settings_name_clear: 'Reset',
        settings_profile: 'Profile',
        settings_profile_status: 'Status',
        settings_profile_not_linked: 'Not linked',
        settings_profile_folder: 'Linked folder',
        settings_profile_folder_desc: 'Live-sync settings, apps and app data to a local folder (Chromium only).',
        settings_profile_pick: 'Pick folder…',
        settings_profile_reconnect: 'Reconnect',
        settings_profile_unlink: 'Unlink',
        settings_profile_export: 'Export .zip',
        settings_profile_export_desc: 'Download a snapshot of the current profile.',
        settings_profile_export_btn: 'Export',
        settings_profile_import: 'Import .zip',
        settings_profile_import_desc: 'Load a previously exported profile (replaces current state).',
        settings_profile_import_btn: 'Import',
        settings_profile_help: 'Copy the folder or .zip between devices to transfer your settings, installed apps, and app data.',
        settings_status_default: 'Default',
        win_minimize: 'Minimize',
        win_maximize: 'Maximize',
        win_close: 'Close',
        start_btn: 'Start',
        start_btn_aria: 'Start menu',
        start_subtitle: 'Tome of the Wandering Mage',
        sysinfo_title: 'System Information',
        sysinfo_btn: 'System Info',
        sysinfo_loading: 'Loading...',
        accent_gold: 'Gold',
        accent_purple: 'Purple',
        accent_cyan: 'Cyan',
        accent_rose: 'Rose',
        accent_emerald: 'Emerald',
        accent_custom: 'Custom',
        font_default: 'Arcane (Cinzel + Inter)',
        font_medieval: 'Medieval (IM Fell)',
        font_modern: 'Modern Sans',
        font_serif: 'Classic Serif',
        font_mono: 'Monospace',
        font_nordic: 'Nordic (Cinzel only)',
        settings_reset_btn: 'Reset',
        settings_wipe_settings_btn: 'Wipe',
        settings_wipe_all_btn: 'Wipe All'
    },
    es: {
        char_class: 'Streamer · Programador · Aventurero',
        sec_home:   'Inicio',
        sec_about:  'Sobre mí',
        sec_live:   'En Vivo',
        sec_links:  'Enlaces',
        live_title: 'Reame en Vivo',
        live_desc: 'Observa al mago en acción a través del portal',
        live_offline: 'El mago no est\u00e1 en el reino... s\u00edguelo para ser notificado del pr\u00f3ximo ritual.',
        links_desc: 'Encuéntrame en estas plataformas',
        bio: 'Me llamo Stefano Aruta. Programador apasionado con un profundo amor por el anime, manga, Ultima Online, Minecraft y D&D. Como los protagonistas de las historias isekai, me lanzo ahora a un nuevo viaje: el streaming. Buscando mundos sin límites donde la libertad y la creatividad no tienen fronteras.',
        boot: [
            '✦ Un alma despierta en este reino...',
            '⊕ Consultando el Tomo Antiguo...',
            '⋆ Los Cuatro Elementos responden...',
            '✦ El círculo mágico toma forma...',
            '⊕ El portal se abre...',
            '✦ Bienvenido al Reino de Aruta ✦'
        ],
        int_gaming:    'Gaming',
        int_anime:     'Anime y Manga',
        int_coding:    'Programación',
        int_streaming: 'Streaming',
        int_fantasy:   'Fantasía y RPG',
        int_openworld: 'Mundo Abierto',
        projects_title: 'Proyectos Actuales',
        proj_stars: 'estrellas',
        proj_forks: 'forks',
        proj_commits: 'commits',
        proj_issues: 'issues',
        proj_created: 'Creado',
        proj_updated: 'Actualizado',
        proj_loading: 'Consultando los archivos...',
        proj_error: 'Pergamino no encontrado',
        live_schedule_title: '✦ Próximos Rituales ✦',
        live_day_tue: 'Martes',
        live_day_thu: 'Jueves',
        live_day_sat: 'Sábado',
        live_countdown: 'Próximo ritual en',
        discord_title: 'Gremio Arcano',
        clips_title: 'Momentos Épicos',
        sec_settings: 'Configuración',
        settings_appearance: 'Apariencia',
        settings_theme: 'Tema',
        settings_theme_desc: 'Cambiar entre modo claro y oscuro',
        settings_fontsize: 'Tamaño de fuente',
        settings_fontsize_desc: 'Ajustar el tamaño del texto',
        settings_accent: 'Color de acento',
        settings_accent_desc: 'Elige tu color de acento',
        settings_clock: 'Reloj',
        settings_showdate: 'Mostrar fecha',
        settings_showdate_desc: 'Mostrar la fecha en la barra',
        settings_24h: 'Formato 24h',
        settings_24h_desc: 'Usar formato de 24 horas',
        settings_sound: 'Sonido',
        settings_ambient: 'Sonido ambiental',
        settings_ambient_desc: 'Drone místico de fondo',
        settings_language: 'Idioma',
        settings_lang: 'Idioma',
        settings_lang_desc: 'Selecciona tu idioma',
        settings_about: 'Acerca de',
        settings_reset: 'Restablecer predeterminados',
        settings_reset_desc: 'Restablecer toda la configuración',
        settings_wipe: 'Borrar datos locales',
        settings_wipe_desc: 'Elimina todos los datos guardados localmente y recarga la página',
        settings_wipe_confirm: '¿Borrar todos los datos locales y recargar la página?',
        toast_reset_done: 'Configuración restablecida',
        toast_wipe_done: 'Datos locales borrados. Recargando…',
        confirm_wipe: 'Borrar',
        confirm_cancel: 'Cancelar',
        start_share: 'Compartir',
        settings_performance: 'Rendimiento',
        settings_particles: 'Partículas',
        settings_particles_desc: 'Efectos de partículas rúnicas',
        settings_fog: 'Niebla',
        settings_fog_desc: 'Capas de niebla ambiental',
        settings_parallax: 'Paralaje',
        settings_parallax_desc: 'Efecto paralaje del ratón',
        settings_cursor: 'Cursor mágico',
        settings_cursor_desc: 'Cursor personalizado',
        settings_clickspells: 'Hechizos de clic',
        settings_clickspells_desc: 'Explosión rúnica al hacer clic',
        settings_circles: 'Círculos mágicos',
        settings_circles_desc: 'Animaciones de anillos giratorios',
        sec_terminal: 'Terminal',
        settings_font: 'Fuente',
        settings_font_desc: 'Familia tipográfica del sitio',
        settings_permissions: 'Permisos',
        settings_widgets: 'Widgets',
        settings_widgets_desc: 'Mini paneles flotantes de los paquetes instalados. Los widgets activos permanecen fijos en el escritorio.',
        widgets_empty: 'No hay widgets disponibles. Instala un paquete que proporcione uno.',
        widgets_mobile_disabled: 'Los widgets están ocultos en pantallas móviles.',
        widget_uninstall_warning: 'Widget desactivado antes de desinstalar',
        settings_install_pkg: 'Instalar paquete',
        settings_install_pkg_desc: 'Importa un .zip con manifest.json + index.js',
        settings_wipe_settings: 'Borrar solo ajustes',
        settings_wipe_settings_desc: 'Restablece preferencias pero conserva apps, comandos y permisos',
        settings_wipe_settings_confirm: '¿Restablecer preferencias? Apps, comandos y sus permisos se conservarán.',
        toast_wipe_settings_done: 'Ajustes restablecidos. Recargando…',
        install_install: 'Instalar',
        install_update: 'Actualizar',
        install_title: '¿Instalar {name}?',
        install_update_title: '¿Actualizar {name}?',
        install_body: 'Tipo: {type}\nID: {id}\nVersión: {version}\nAutor: {author}\n\nPermisos declarados:\n{perms}',
        install_no_perms: '(ninguno)',
        install_installed: '{name} instalado',
        install_updated: '{name} actualizado',
        install_err_not_zip: 'El archivo debe ser un .zip',
        install_err_invalid: 'Manifiesto inválido',
        install_drop_label: 'Suelta un .zip para instalar',
        term_welcome: '✦ Terminal Aruta — escribe "help" para ver los comandos',
        term_help_header: 'Comandos integrados:',
        term_help_custom: 'Comandos instalados:',
        term_unknown: 'comando desconocido:',
        perm_request_title: '{name} quiere acceder a {perm}',
        perm_deny: 'Denegar',
        perm_allow_once: 'Permitir',
        perm_allow_always: 'Siempre',
        perm_grant: 'Conceder',
        perm_revoke: 'Revocar',
        perm_uninstall: 'Desinstalar',
        perm_uninstall_confirm: '¿Desinstalar {name}?',
        perm_uninstalled: '{name} desinstalado',
        perm_empty: 'Sin paquetes instalados.',
        perm_no_perms: 'Sin permisos usados.',
        perm_state_granted: 'concedido',
        perm_state_denied: 'denegado',
        perm_state_ask: 'preguntar',
        perm_storage: 'almacenamiento local',
        perm_storage_desc: 'Guardar y leer sus propios datos persistentes.',
        perm_notifications: 'notificaciones',
        perm_notifications_desc: 'Mostrar avisos en la interfaz.',
        perm_windows: 'ventanas',
        perm_windows_desc: 'Abrir o cerrar otras ventanas del sistema.',
        perm_terminal: 'terminal',
        perm_terminal_desc: 'Imprimir texto en el terminal.',
        perm_fetch: 'red',
        perm_fetch_desc: 'Hacer peticiones HTTP a dominios externos.',
        perm_theme: 'tema',
        perm_theme_desc: 'Leer y cambiar el tema (claro/oscuro).',
        perm_clipboard: 'portapapeles',
        perm_clipboard_desc: 'Leer o escribir el portapapeles del sistema.',
        perm_install: 'instalar',
        perm_install_desc: 'Enviar un paquete .zip al instalador. La confirmación final sigue siendo tuya.',
        cat_info: 'Información',
        cat_games: 'Juegos',
        cat_tools: 'Herramientas',
        cat_creativity: 'Creatividad',
        cat_other: 'Otros',
        cat_system: 'Sistema',
        settings_theme_follow: 'Seguir el tema del sistema',
        settings_theme_follow_desc: 'Adapta automáticamente claro/oscuro a tu SO',
        settings_bg: 'Fondo',
        settings_bg_desc: 'Imagen o vídeo personalizado (guardado en tu perfil)',
        settings_bg_pick: 'Subir…',
        settings_bg_clear: 'Quitar',
        settings_portrait: 'Retrato',
        settings_portrait_desc: 'Reemplaza la imagen del héroe',
        settings_portrait_pick: 'Subir…',
        settings_portrait_clear: 'Restablecer',
        settings_name: 'Nombre mostrado',
        settings_name_desc: 'Se muestra en la portada y en el menú de inicio',
        settings_name_clear: 'Restablecer',
        settings_profile: 'Perfil',
        settings_profile_status: 'Estado',
        settings_profile_not_linked: 'No vinculado',
        settings_profile_folder: 'Carpeta vinculada',
        settings_profile_folder_desc: 'Sincroniza ajustes, apps y datos con una carpeta local (solo Chromium).',
        settings_profile_pick: 'Elegir carpeta…',
        settings_profile_reconnect: 'Reconectar',
        settings_profile_unlink: 'Desvincular',
        settings_profile_export: 'Exportar .zip',
        settings_profile_export_desc: 'Descarga una instantánea del perfil actual.',
        settings_profile_export_btn: 'Exportar',
        settings_profile_import: 'Importar .zip',
        settings_profile_import_desc: 'Carga un perfil exportado (reemplaza el estado actual).',
        settings_profile_import_btn: 'Importar',
        settings_profile_help: 'Copia la carpeta o el .zip entre dispositivos para transferir ajustes, apps y datos.',
        settings_status_default: 'Predeterminado',
        win_minimize: 'Minimizar',
        win_maximize: 'Maximizar',
        win_close: 'Cerrar',
        start_btn: 'Inicio',
        start_btn_aria: 'Menú de inicio',
        start_subtitle: 'Tomo del Mago Errante',
        sysinfo_title: 'Información del sistema',
        sysinfo_btn: 'Info sistema',
        sysinfo_loading: 'Cargando...',
        accent_gold: 'Oro',
        accent_purple: 'Violeta',
        accent_cyan: 'Cian',
        accent_rose: 'Rosa',
        accent_emerald: 'Esmeralda',
        accent_custom: 'Personalizado',
        font_default: 'Arcano (Cinzel + Inter)',
        font_medieval: 'Medieval (IM Fell)',
        font_modern: 'Moderno Sans',
        font_serif: 'Serif Clásico',
        font_mono: 'Monospace',
        font_nordic: 'Nórdico (solo Cinzel)',
        settings_reset_btn: 'Restablecer',
        settings_wipe_settings_btn: 'Borrar',
        settings_wipe_all_btn: 'Borrar todo'
    },
    ja: {
        char_class: 'ストリーマー · プログラマー · 冒険者',
        sec_home:   'ホーム',
        sec_about:  'について',
        sec_live:   'ライブ',
        sec_links:  'リンク',
        live_title: 'ライブ王国',
        live_desc: 'ポータルを通じて魔法使いの活動を見よう',
        live_offline: '魔法使いは王国にいません... 次の儀式の通知を受け取るにはフォローしてください。',
        links_desc: 'これらのプラットフォームで見つけてください',
        bio: '私はStefano Arutaです。アニメ、マンガ、ウルティマオンライン、マインクラフト、D&Dへの深い愛を持つ情熱的なプログラマーです。異世界転生の主人公のように、今私は新たな旅へ踏み出します——ストリーミングの世界へ。自由と創造性に限界のない世界を求めて。',
        boot: [
            '✦ この王国に魂が目覚める...',
            '⊕ 古代の書を開く...',
            '⋆ 四つの元素が応答する...',
            '✦ 魔法陣が形を成す...',
            '⊕ 転移門が開く...',
            '✦ アルタの王国へようこそ ✦'
        ],
        int_gaming:    'ゲーム',
        int_anime:     'アニメ & マンガ',
        int_coding:    'プログラミング',
        int_streaming: 'ストリーミング',
        int_fantasy:   'ファンタジー & RPG',
        int_openworld: 'オープンワールド',
        projects_title: '進行中のプロジェクト',
        proj_stars: 'スター',
        proj_forks: 'フォーク',
        proj_commits: 'コミット',
        proj_issues: 'イシュー',
        proj_created: '作成日',
        proj_updated: '更新日',
        proj_loading: '古文書を調べています...',
        proj_error: '巻物が見つかりません',
        live_schedule_title: '✦ 次の儀式 ✦',
        live_day_tue: '火曜日',
        live_day_thu: '木曜日',
        live_day_sat: '土曜日',
        live_countdown: '次の儀式まで',
        discord_title: '秘術のギルド',
        clips_title: '名場面',
        sec_settings: '設定',
        settings_appearance: '外観',
        settings_theme: 'テーマ',
        settings_theme_desc: 'ダーク/ライトモードの切替',
        settings_fontsize: 'フォントサイズ',
        settings_fontsize_desc: 'テキストサイズの調整',
        settings_accent: 'アクセントカラー',
        settings_accent_desc: 'メインカラーの選択',
        settings_clock: '時計',
        settings_showdate: '日付表示',
        settings_showdate_desc: 'バーに日付を表示',
        settings_24h: '24時間形式',
        settings_24h_desc: '24時間表示を使用',
        settings_sound: 'サウンド',
        settings_ambient: '環境音',
        settings_ambient_desc: '神秘的な背景ドローン',
        settings_language: '言語',
        settings_lang: '言語',
        settings_lang_desc: '言語を選択',
        settings_about: '情報',
        settings_reset: 'デフォルトに戻す',
        settings_reset_desc: 'すべての設定をリセット',
        settings_wipe: 'ローカルデータを消去',
        settings_wipe_desc: 'ローカルに保存されたすべてのデータを削除してページを再読み込み',
        settings_wipe_confirm: 'ローカルデータをすべて削除してページを再読み込みしますか？',
        toast_reset_done: '設定をリセットしました',
        toast_wipe_done: 'ローカルデータを削除しました。再読み込み中…',
        confirm_wipe: '削除',
        confirm_cancel: 'キャンセル',
        start_share: '共有',
        settings_performance: 'パフォーマンス',
        settings_particles: 'パーティクル',
        settings_particles_desc: 'ルーン粒子エフェクト',
        settings_fog: 'フォグ',
        settings_fog_desc: '環境フォグレイヤー',
        settings_parallax: 'パララックス',
        settings_parallax_desc: 'マウスパララックス効果',
        settings_cursor: 'マジックカーソル',
        settings_cursor_desc: 'カスタムカーソル',
        settings_clickspells: 'クリック魔法',
        settings_clickspells_desc: 'クリック時ルーン爆発',
        settings_circles: '魔法陣',
        settings_circles_desc: '回転リングアニメーション',
        sec_terminal: 'ターミナル',
        settings_font: 'フォント',
        settings_font_desc: 'サイト全体のフォントファミリ',
        settings_permissions: '権限',
        settings_widgets: 'ウィジェット',
        settings_widgets_desc: 'インストール済みパッケージからのミニパネル。有効化されたウィジェットはデスクトップに固定されます。',
        widgets_empty: '利用可能なウィジェットがありません。提供するパッケージをインストールしてください。',
        widgets_mobile_disabled: 'モバイル画面ではウィジェットは非表示です。',
        widget_uninstall_warning: 'アンインストール前にウィジェットを無効化しました',
        settings_install_pkg: 'パッケージをインストール',
        settings_install_pkg_desc: 'manifest.json と index.js を含む .zip をインポート',
        settings_wipe_settings: '設定のみ消去',
        settings_wipe_settings_desc: '設定をリセットし、アプリ・コマンド・権限は維持',
        settings_wipe_settings_confirm: '設定をリセットしますか？ アプリ・コマンド・権限は保持されます。',
        toast_wipe_settings_done: '設定をリセットしました。再読込…',
        install_install: 'インストール',
        install_update: '更新',
        install_title: '{name} をインストールしますか？',
        install_update_title: '{name} を更新しますか？',
        install_body: 'タイプ: {type}\nID: {id}\nバージョン: {version}\n作者: {author}\n\n宣言された権限:\n{perms}',
        install_no_perms: '(なし)',
        install_installed: '{name} をインストールしました',
        install_updated: '{name} を更新しました',
        install_err_not_zip: 'ファイルは .zip でなければなりません',
        install_err_invalid: '無効なマニフェスト',
        install_drop_label: '.zip をドロップしてインストール',
        term_welcome: '✦ Aruta ターミナル — "help" でコマンド一覧',
        term_help_header: '組み込みコマンド:',
        term_help_custom: 'インストール済みコマンド:',
        term_unknown: '不明なコマンド:',
        perm_request_title: '{name} が {perm} へのアクセスを要求',
        perm_deny: '拒否',
        perm_allow_once: '許可',
        perm_allow_always: '常に許可',
        perm_grant: '許可',
        perm_revoke: '取り消し',
        perm_uninstall: 'アンインストール',
        perm_uninstall_confirm: '{name} をアンインストールしますか？',
        perm_uninstalled: '{name} をアンインストールしました',
        perm_empty: 'インストール済みパッケージはありません。',
        perm_no_perms: '使用中の権限はありません。',
        perm_state_granted: '許可',
        perm_state_denied: '拒否',
        perm_state_ask: '要確認',
        perm_storage: 'ローカルストレージ',
        perm_storage_desc: '自分のデータを保存・読み取りします。',
        perm_notifications: '通知',
        perm_notifications_desc: 'UIにトーストを表示します。',
        perm_windows: 'ウィンドウ',
        perm_windows_desc: '他のシステムウィンドウを開閉します。',
        perm_terminal: 'ターミナル',
        perm_terminal_desc: 'ターミナルにテキストを出力します。',
        perm_fetch: 'ネットワーク',
        perm_fetch_desc: '外部ドメインへHTTPリクエストを行います。',
        perm_theme: 'テーマ',
        perm_theme_desc: 'テーマ(明暗)を読み取り・変更します。',
        perm_clipboard: 'クリップボード',
        perm_clipboard_desc: 'システムのクリップボードを読み書きします。',
        perm_install: 'インストール',
        perm_install_desc: '.zipパッケージをインストーラーへ送信します。最終確認は常にあなたが行います。',
        cat_info: '情報',
        cat_games: 'ゲーム',
        cat_tools: 'ツール',
        cat_creativity: 'クリエイティブ',
        cat_other: 'その他',
        cat_system: 'システム',
        settings_theme_follow: 'システムテーマに従う',
        settings_theme_follow_desc: 'OSのダーク/ライト設定に自動で合わせる',
        settings_bg: '背景',
        settings_bg_desc: 'カスタム画像またはビデオループ（プロファイルに保存）',
        settings_bg_pick: 'アップロード…',
        settings_bg_clear: 'クリア',
        settings_portrait: 'ポートレート',
        settings_portrait_desc: 'ヒーロー画像を置き換える',
        settings_portrait_pick: 'アップロード…',
        settings_portrait_clear: 'リセット',
        settings_name: '表示名',
        settings_name_desc: 'ヒーロー欄と起動メニューに表示',
        settings_name_clear: 'リセット',
        settings_profile: 'プロフィール',
        settings_profile_status: '状態',
        settings_profile_not_linked: '未リンク',
        settings_profile_folder: 'リンクされたフォルダ',
        settings_profile_folder_desc: '設定・アプリ・アプリデータをローカルフォルダと同期（Chromiumのみ）。',
        settings_profile_pick: 'フォルダを選択…',
        settings_profile_reconnect: '再接続',
        settings_profile_unlink: 'リンク解除',
        settings_profile_export: '.zip をエクスポート',
        settings_profile_export_desc: '現在のプロファイルのスナップショットをダウンロード。',
        settings_profile_export_btn: 'エクスポート',
        settings_profile_import: '.zip をインポート',
        settings_profile_import_desc: 'エクスポートしたプロファイルを読み込む（現在の状態を上書き）。',
        settings_profile_import_btn: 'インポート',
        settings_profile_help: 'フォルダまたは .zip をコピーして設定・アプリ・データを他デバイスへ移行。',
        settings_status_default: 'デフォルト',
        win_minimize: '最小化',
        win_maximize: '最大化',
        win_close: '閉じる',
        start_btn: 'スタート',
        start_btn_aria: 'スタートメニュー',
        start_subtitle: 'さすらう魔法使いの書',
        sysinfo_title: 'システム情報',
        sysinfo_btn: 'システム情報',
        sysinfo_loading: '読み込み中...',
        accent_gold: 'ゴールド',
        accent_purple: 'パープル',
        accent_cyan: 'シアン',
        accent_rose: 'ローズ',
        accent_emerald: 'エメラルド',
        accent_custom: 'カスタム',
        font_default: 'アルケイン (Cinzel + Inter)',
        font_medieval: '中世 (IM Fell)',
        font_modern: 'モダン Sans',
        font_serif: 'クラシック Serif',
        font_mono: 'Monospace',
        font_nordic: 'ノルディック (Cinzelのみ)',
        settings_reset_btn: 'リセット',
        settings_wipe_settings_btn: '消去',
        settings_wipe_all_btn: 'すべて消去'
    },
    fn: {
        char_class: 'ᛊᛏᚱᛖᚨᛗᛖᚱ · ᛈᚱᛟᚷᚱᚨᛗᛗᛖᚱ · ᚨᛞᚹᛖᚾᛏᚢᚱᛖᚱ',
        sec_home:   'ᚺᛟᛗᛖ',
        sec_about:  'ᚨᛒᛟᚢᛏ',
        sec_live:   'ᛚᛁᚹᛖ',
        sec_links:  'ᛚᛁᚾᚲᛊ',
        live_title: 'ᛚᛁᚹᛖ ᚱᛖᚨᛚᛗ',
        live_desc: 'ᚹᚨᛏᚲᚺ ᚦᛖ ᛗᚨᚷᛖ ᛁᚾ ᚨᚲᛏᛁᛟᚾ',
        live_offline: 'ᚦᛖ ᛗᚨᚷᛖ ᛁᛊ ᚾᛟᛏ ᛁᚾ ᚦᛖ ᚱᛖᚨᛚᛗ...',
        links_desc: 'ᚠᛁᚾᛞ ᛗᛖ ᛟᚾ ᚦᛖᛊᛖ ᛈᛚᚨᛏᚠᛟᚱᛗᛊ',
        bio: 'ᛁ ᚨᛗ ᛊᛏᛖᚠᚨᚾᛟ ᚨᚱᚢᛏᚨ · ᚨ ᛈᚨᛊᛊᛁᛟᚾᚨᛏᛖ ᛈᚱᛟᚷᚱᚨᛗᛗᛖᚱ ᚹᛁᛏᚺ ᚨ ᛞᛖᛖᛈ ᛚᛟᚹᛖ ᚠᛟᚱ ᚨᚾᛁᛗᛖ · ᛗᚨᚾᚷᚨ · ᚢᛚᛏᛁᛗᚨ ᛟᚾᛚᛁᚾᛖ · ᛗᛁᚾᛖᚲᚱᚨᚠᛏ ᚨᚾᛞ ᛞᚨᚾᛞ · ᛚᛁᚲᛖ ᚦᛖ ᚺᛖᚱᛟᛖᛊ ᛟᚠ ᛁᛊᛖᚲᚨᛁ ᛏᚨᛚᛖᛊ · ᛁ ᚾᛟᚹ ᛖᛗᛒᚨᚱᚲ ᛟᚾ ᚨ ᚾᛖᚹ ᛃᛟᚢᚱᚾᛖᛃ · ᛊᛏᚱᛖᚨᛗᛁᚾᚷ · ᛊᛖᛖᚲᛁᚾᚷ ᚹᛟᚱᛚᛞᛊ ᚹᛁᛏᚺᛟᚢᛏ ᛒᛟᚢᚾᛞᚨᚱᛁᛖᛊ',
        boot: [
            '✦ ᚨ ᛊᛟᚢᛚ ᚨᚹᚨᚲᛖᚾᛊ ᛁᚾ ᚦᛁᛊ ᚱᛖᚨᛚᛗ...',
            '⊕ ᚲᛟᚾᛊᚢᛚᛏᛁᚾᚷ ᚦᛖ ᚨᚾᚲᛁᛖᚾᛏ ᛏᛟᛗᛖ...',
            '⋆ ᚦᛖ ᚠᛟᚢᚱ ᛖᛚᛖᛗᛖᚾᛏᛊ ᚱᛖᛊᛈᛟᚾᛞ...',
            '✦ ᚦᛖ ᛗᚨᚷᛁᚲ ᚲᛁᚱᚲᛚᛖ ᛏᚨᚲᛖᛊ ᛊᚺᚨᛈᛖ...',
            '⊕ ᚦᛖ ᛈᛟᚱᛏᚨᛚ ᛟᛈᛖᚾᛊ...',
            '✦ ᚹᛖᛚᚲᛟᛗᛖ ᛏᛟ ᚦᛖ ᚱᛖᚨᛚᛗ ᛟᚠ ᚨᚱᚢᛏᚨ ✦'
        ],
        int_gaming:    'ᚷᚨᛗᛁᚾᚷ',
        int_anime:     'ᚨᚾᛁᛗᛖ & ᛗᚨᚾᚷᚨ',
        int_coding:    'ᛈᚱᛟᚷᚱᚨᛗᛗᛁᚾᚷ',
        int_streaming: 'ᛊᛏᚱᛖᚨᛗᛁᚾᚷ',
        int_fantasy:   'ᚠᚨᚾᛏᚨᛊᛃ & ᚱᛈᚷ',
        int_openworld: 'ᛟᛈᛖᚾ ᚹᛟᚱᛚᛞ',
        projects_title: 'ᛈᚱᛟᛃᛖᚲᛏᛊ',
        proj_stars: 'ᛊᛏᚨᚱᛊ',
        proj_forks: 'ᚠᛟᚱᚲᛊ',
        proj_commits: 'ᚲᛟᛗᛗᛁᛏᛊ',
        proj_issues: 'ᛁᛊᛊᚢᛖᛊ',
        proj_created: 'ᚲᚱᛖᚨᛏᛖᛞ',
        proj_updated: 'ᚢᛈᛞᚨᛏᛖᛞ',
        proj_loading: 'ᚲᛟᚾᛊᚢᛚᛏᛁᚾᚷ...',
        proj_error: 'ᛊᚲᚱᛟᛚᛚ ᚾᛟᛏ ᚠᛟᚢᚾᛞ',
        live_schedule_title: '✦ ᚢᛈᚲᛟᛗᛁᚾᚷ ᚱᛁᛏᚢᚨᛚᛊ ✦',
        live_day_tue: 'ᛏᚢᛖᛊᛞᚨᛃ',
        live_day_thu: 'ᚦᚢᚱᛊᛞᚨᛃ',
        live_day_sat: 'ᛊᚨᛏᚢᚱᛞᚨᛃ',
        live_countdown: 'ᚾᛖᚲᛊᛏ ᚱᛁᛏᚢᚨᛚ ᛁᚾ',
        discord_title: 'ᚨᚱᚲᚨᚾᛖ ᚷᚢᛁᛚᛞ',
        clips_title: 'ᛖᛈᛁᚲ ᛗᛟᛗᛖᚾᛏᛊ',
        sec_settings: 'ᛊᛖᛏᛏᛁᚾᚷᛊ',
        settings_appearance: 'ᚨᛈᛈᛖᚨᚱᚨᚾᚲᛖ',
        settings_theme: 'ᚦᛖᛗᛖ',
        settings_theme_desc: 'ᛞᚨᚱᚲ / ᛚᛁᚷᚺᛏ',
        settings_fontsize: 'ᚠᛟᚾᛏ ᛊᛁᛉᛖ',
        settings_fontsize_desc: 'ᛏᛖᚲᛊᛏ ᛊᛁᛉᛖ',
        settings_accent: 'ᚨᚲᚲᛖᚾᛏ',
        settings_accent_desc: 'ᚲᛟᛚᛟᚱ',
        settings_clock: 'ᚲᛚᛟᚲᚲ',
        settings_showdate: 'ᛊᚺᛟᚹ ᛞᚨᛏᛖ',
        settings_showdate_desc: 'ᛞᚨᛏᛖ ᛁᚾ ᛒᚨᚱ',
        settings_24h: '24ᚺ',
        settings_24h_desc: '24ᚺ ᚠᛟᚱᛗᚨᛏ',
        settings_sound: 'ᛊᛟᚢᚾᛞ',
        settings_ambient: 'ᚨᛗᛒᛁᛖᚾᛏ',
        settings_ambient_desc: 'ᛞᚱᛟᚾᛖ',
        settings_language: 'ᛚᚨᚾᚷᚢᚨᚷᛖ',
        settings_lang: 'ᛚᚨᚾᚷ',
        settings_lang_desc: 'ᛊᛖᛚᛖᚲᛏ',
        settings_about: 'ᚨᛒᛟᚢᛏ',
        settings_reset: 'ᚱᛖᛊᛖᛏ',
        settings_reset_desc: 'ᛞᛖᚠᚨᚢᛚᛏᛊ',
        settings_wipe: 'ᚹᛁᛈᛖ',
        settings_wipe_desc: 'ᛞᛖᛚᛖᛏᛖ ᚨᛚᛚ ᛚᚩᚳᚨᛚ ᛞᚨᛏᚨ',
        settings_wipe_confirm: 'ᚹᛁᛈᛖ ᚨᛚᛚ ᛞᚨᛏᚨ?',
        toast_reset_done: 'ᚱᛖᛊᛖᛏ ᛞᚩᚾᛖ',
        toast_wipe_done: 'ᚹᛁᛈᛖᛞ. ᚱᛖᛚᚩᚨᛞᛁᛝ…',
        confirm_wipe: 'ᚹᛁᛈᛖ',
        confirm_cancel: 'ᚾᚩ',
        start_share: 'ᛊᚺᚨᚱᛖ',
        settings_performance: 'ᛈᛖᚱᚠ',
        settings_particles: 'ᛈᚨᚱᛏᛁᚲᛚᛖᛊ',
        settings_particles_desc: 'ᚱᚢᚾᛖᛊ',
        settings_fog: 'ᚠᛟᚷ',
        settings_fog_desc: 'ᚠᛟᚷ',
        settings_parallax: 'ᛈᚨᚱᚨᛚᛚᚨᚲᛊ',
        settings_parallax_desc: 'ᛗᛟᚢᛊᛖ',
        settings_cursor: 'ᚲᚢᚱᛊᛟᚱ',
        settings_cursor_desc: 'ᚲᚢᛊᛏᛟᛗ',
        settings_clickspells: 'ᛊᛈᛖᛚᛚᛊ',
        settings_clickspells_desc: 'ᚲᛚᛁᚲᚲ',
        settings_circles: 'ᚲᛁᚱᚲᛚᛖᛊ',
        settings_circles_desc: 'ᚱᛁᚾᚷᛊ',
        sec_terminal: 'ᛏᛖᚱᛗᛁᚾᚨᛚ',
        settings_font: 'ᚠᛟᚾᛏ',
        settings_font_desc: 'ᚠᛟᚾᛏ ᚠᚨᛗᛁᛚᛃ',
        settings_permissions: 'ᛈᛖᚱᛗᛁᛊᛊᛁᛟᚾᛊ',
        settings_widgets: 'ᚹᛁᛞᚷᛖᛏᛊ',
        settings_widgets_desc: 'ᚠᛚᛟᚨᛏᛁᚾᚷ ᛗᛁᚾᛁ ᛈᚨᚾᛖᛚᛊ',
        widgets_empty: 'ᚾᛟ ᚹᛁᛞᚷᛖᛏᛊ',
        widgets_mobile_disabled: 'ᚾᛟ ᛗᛟᛒᛁᛚᛖ',
        widget_uninstall_warning: 'ᚹᛁᛞᚷᛖᛏ ᛞᛁᛊᚨᛒᛚᛖᛞ',
        settings_install_pkg: 'ᛁᚾᛊᛏᚨᛚᛚ ᛈᚨᚲᚲᚨᚷᛖ',
        settings_install_pkg_desc: 'ᛁᛗᛈᛟᚱᛏ .ᛉᛁᛈ',
        settings_wipe_settings: 'ᚹᛁᛈᛖ ᛊᛖᛏᛏᛁᚾᚷᛊ',
        settings_wipe_settings_desc: 'ᚱᛖᛊᛖᛏ ᛈᚱᛖᚠᛊ',
        settings_wipe_settings_confirm: 'ᚱᛖᛊᛖᛏ ᛊᛖᛏᛏᛁᚾᚷᛊ?',
        toast_wipe_settings_done: 'ᚹᛁᛈᛖᛞ. ᚱᛖᛚᛟᚨᛞᛁᚾᚷ…',
        install_install: 'ᛁᚾᛊᛏᚨᛚᛚ',
        install_update: 'ᚢᛈᛞᚨᛏᛖ',
        install_title: 'ᛁᚾᛊᛏᚨᛚᛚ {name}?',
        install_update_title: 'ᚢᛈᛞᚨᛏᛖ {name}?',
        install_body: 'ᛏᛃᛈᛖ: {type}\nᛁᛞ: {id}\nᚹᛖᚱᛊᛁᛟᚾ: {version}\nᚨᚢᛏᚺᛟᚱ: {author}\n\nᛈᛖᚱᛗᛊ:\n{perms}',
        install_no_perms: '(ᚾᛟᚾᛖ)',
        install_installed: '{name} ᛁᚾᛊᛏᚨᛚᛚᛖᛞ',
        install_updated: '{name} ᚢᛈᛞᚨᛏᛖᛞ',
        install_err_not_zip: 'ᚠᛁᛚᛖ ᛗᚢᛊᛏ ᛒᛖ .ᛉᛁᛈ',
        install_err_invalid: 'ᛁᚾᚹᚨᛚᛁᛞ ᛗᚨᚾᛁᚠᛖᛊᛏ',
        install_drop_label: 'ᛞᚱᛟᛈ .ᛉᛁᛈ',
        term_welcome: '✦ ᚨᚱᚢᛏᚨ ᛏᛖᚱᛗ — "help"',
        term_help_header: 'ᚲᛟᛗᛗᚨᚾᛞᛊ:',
        term_help_custom: 'ᛁᚾᛊᛏᚨᛚᛚᛖᛞ:',
        term_unknown: 'ᚢᚾᚴᚾᛟᚹᚾ:',
        perm_request_title: '{name} → {perm}',
        perm_deny: 'ᛞᛖᚾᛃ',
        perm_allow_once: 'ᚨᛚᛚᛟᚹ',
        perm_allow_always: 'ᚨᛚᚹᚨᛃᛊ',
        perm_grant: 'ᚷᚱᚨᚾᛏ',
        perm_revoke: 'ᚱᛖᚹᛟᚴᛖ',
        perm_uninstall: 'ᚢᚾᛁᚾᛊᛏᚨᛚᛚ',
        perm_uninstall_confirm: 'ᚢᚾᛁᚾᛊᛏᚨᛚᛚ {name}?',
        perm_uninstalled: '{name} ᚢᚾᛁᚾᛊᛏᚨᛚᛚᛖᛞ',
        perm_empty: 'ᚾᛟ ᛈᚨᚲᚲᚨᚷᛖᛊ',
        perm_no_perms: 'ᚾᛟ ᛈᛖᚱᛗᛊ',
        perm_state_granted: 'ᚷᚱᚨᚾᛏᛖᛞ',
        perm_state_denied: 'ᛞᛖᚾᛁᛖᛞ',
        perm_state_ask: 'ᚨᛊᚴ',
        perm_storage: 'ᛊᛏᛟᚱᚨᚷᛖ',
        perm_storage_desc: 'ᛊᚨᚹᛖ ᛞᚨᛏᚨ',
        perm_notifications: 'ᚾᛟᛏᛁᚠᛃ',
        perm_notifications_desc: 'ᛊᚺᛟᚹ ᛏᛟᚨᛊᛏᛊ',
        perm_windows: 'ᚹᛁᚾᛞᛟᚹᛊ',
        perm_windows_desc: 'ᛟᛈᛖᚾ ᚲᛚᛟᛊᛖ',
        perm_terminal: 'ᛏᛖᚱᛗ',
        perm_terminal_desc: 'ᛈᚱᛁᚾᛏ',
        perm_fetch: 'ᚾᛖᛏ',
        perm_fetch_desc: 'ᚺᛏᛏᛈ',
        perm_theme: 'ᛏᚺᛖᛗᛖ',
        perm_theme_desc: 'ᚱᛖᚨᛞ ᛏᚺᛖᛗᛖ',
        perm_clipboard: 'ᚲᛚᛁᛈ',
        perm_clipboard_desc: 'ᚱᛖᚨᛞ ᚹᚱᛁᛏᛖ',
        perm_install: 'ᛁᚾᛋᛏ',
        perm_install_desc: 'ᛊᚢᛒᛗᛁᛏ ᛉᛁᛈ',
        cat_info: 'ᛁᚾᚠᛟ',
        cat_games: 'ᚷᚨᛗᛖᛊ',
        cat_tools: 'ᛏᛟᛟᛚᛊ',
        cat_creativity: 'ᚲᚱᛖᚨᛏᛁᚹᛁᛏᛃ',
        cat_other: 'ᛟᛏᚺᛖᚱ',
        cat_system: 'ᛊᛃᛊᛏᛖᛗ',
        settings_theme_follow: 'ᚠᛟᛚᛚᛟᚹ ᛟᛊ',
        settings_theme_follow_desc: 'ᛟᛊ ᚦᛖᛗᛖ',
        settings_bg: 'ᛒᚷ',
        settings_bg_desc: 'ᛁᛗᚷ / ᚹᛁᛞ',
        settings_bg_pick: 'ᚢᛈᛚᛟᚨᛞ',
        settings_bg_clear: 'ᚲᛚᛖᚨᚱ',
        settings_portrait: 'ᛈᛟᚱᛏᚱᚨᛁᛏ',
        settings_portrait_desc: 'ᚺᛖᚱᛟ ᛁᛗᚷ',
        settings_portrait_pick: 'ᚢᛈᛚᛟᚨᛞ',
        settings_portrait_clear: 'ᚱᛖᛊᛖᛏ',
        settings_name: 'ᚾᚨᛗᛖ',
        settings_name_desc: 'ᛞᛁᛊᛈᛚᚨᛃ',
        settings_name_clear: 'ᚱᛖᛊᛖᛏ',
        settings_profile: 'ᛈᚱᛟᚠᛁᛚᛖ',
        settings_profile_status: 'ᛊᛏᚨᛏᚢᛊ',
        settings_profile_not_linked: 'ᚾᛟᛏ ᛚᛁᚾᚴᛖᛞ',
        settings_profile_folder: 'ᚠᛟᛚᛞᛖᚱ',
        settings_profile_folder_desc: 'ᛊᛃᚾᚲ ᚠᛟᛚᛞᛖᚱ',
        settings_profile_pick: 'ᛈᛁᚲᚴ',
        settings_profile_reconnect: 'ᚱᛖᚲᛟᚾ',
        settings_profile_unlink: 'ᚢᚾᛚᛁᚾᚴ',
        settings_profile_export: 'ᛖᚲᛊᛈᛟᚱᛏ .ᛉᛁᛈ',
        settings_profile_export_desc: 'ᛊᚾᚨᛈᛊᚺᛟᛏ',
        settings_profile_export_btn: 'ᛖᚲᛊᛈᛟᚱᛏ',
        settings_profile_import: 'ᛁᛗᛈᛟᚱᛏ .ᛉᛁᛈ',
        settings_profile_import_desc: 'ᛚᛟᚨᛞ ᛉᛁᛈ',
        settings_profile_import_btn: 'ᛁᛗᛈᛟᚱᛏ',
        settings_profile_help: 'ᚲᛟᛈᛃ ᛒᛖᛏᚹᛖᛖᚾ ᛞᛖᚹᛁᚲᛖᛊ',
        settings_status_default: 'ᛞᛖᚠᚨᚢᛚᛏ',
        win_minimize: 'ᛗᛁᚾ',
        win_maximize: 'ᛗᚨᚲᛊ',
        win_close: 'ᚲᛚᛟᛊᛖ',
        start_btn: 'ᛊᛏᚨᚱᛏ',
        start_btn_aria: 'ᛊᛏᚨᚱᛏ ᛗᛖᚾᚢ',
        start_subtitle: 'ᛏᛟᛗᛖ ᛟᚠ ᚦᛖ ᛗᚨᚷᛖ',
        sysinfo_title: 'ᛊᛃᛊ ᛁᚾᚠᛟ',
        sysinfo_btn: 'ᛊᛃᛊ ᛁᚾᚠᛟ',
        sysinfo_loading: 'ᛚᛟᚨᛞᛁᚾᚷ...',
        accent_gold: 'ᚷᛟᛚᛞ',
        accent_purple: 'ᛈᚢᚱᛈᛚᛖ',
        accent_cyan: 'ᚲᛃᚨᚾ',
        accent_rose: 'ᚱᛟᛊᛖ',
        accent_emerald: 'ᛖᛗᛖᚱᚨᛚᛞ',
        accent_custom: 'ᚲᚢᛊᛏᛟᛗ',
        font_default: 'ᚨᚱᚲᚨᚾᛖ',
        font_medieval: 'ᛗᛖᛞᛁᛖᚹᚨᛚ',
        font_modern: 'ᛗᛟᛞᛖᚱᚾ',
        font_serif: 'ᛊᛖᚱᛁᚠ',
        font_mono: 'ᛗᛟᚾᛟ',
        font_nordic: 'ᚾᛟᚱᛞᛁᚲ',
        settings_reset_btn: 'ᚱᛖᛊᛖᛏ',
        settings_wipe_settings_btn: 'ᚹᛁᛈᛖ',
        settings_wipe_all_btn: 'ᚹᛁᛈᛖ ᚨᛚᛚ'
    }
};

/* ════════════════════════════
   SOCIAL LINKS
════════════════════════════ */
const SOCIALS = [
    { id: 'twitch',    href: 'https://twitch.tv/aruta.sh',     platform: 'Twitch',      handle: 'aruta.sh',  icon: '<i class="fab fa-twitch link-card-icon"></i>' },
    { id: 'kick',      href: 'https://kick.com/aruta_sh',      platform: 'Kick',        handle: 'aruta_sh',  icon: '<svg class="link-card-icon" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M2 2h4v6l4-6h5l-5 7 5 7h-5l-4-6v6H2V2z"/></svg>' },
    { id: 'youtube',   href: 'https://youtube.com/@aruta.sh',  platform: 'YouTube',     handle: '@aruta.sh', icon: '<i class="fab fa-youtube link-card-icon"></i>' },
    { id: 'twitter',   href: 'https://twitter.com/aruta.sh',   platform: 'Twitter / X', handle: '@aruta.sh', icon: '<i class="fab fa-twitter link-card-icon"></i>' },
    { id: 'instagram', href: 'https://instagram.com/aruta_sr', platform: 'Instagram',   handle: 'aruta_sr',  icon: '<i class="fab fa-instagram link-card-icon"></i>' },
    { id: 'github',    href: 'https://github.com/Arutosio',    platform: 'GitHub',      handle: 'Arutosio',  icon: '<i class="fab fa-github link-card-icon"></i>' }
];

/* ════════════════════════════
   PROJECTS — just change the slug to swap a repo
════════════════════════════ */
const PROJECTS = [
    'Arutosio/Hina',
    'Arutosio/AnimeWorldDownloader'
];

/* ════════════════════════════
   INTERESTS
════════════════════════════ */
const INTERESTS = [
    { icon: '🎮', key: 'int_gaming',    detail: 'Ultima Online · Minecraft · D&D' },
    { icon: '🌸', key: 'int_anime',     detail: 'Isekai · Shonen · Seinen' },
    { icon: '💻', key: 'int_coding',    detail: 'Web · Scripts · Automation' },
    { icon: '📺', key: 'int_streaming', detail: 'Twitch · Kick · YouTube' },
    { icon: '⚔️', key: 'int_fantasy',   detail: 'Dungeons & Dragons · Roleplay' },
    { icon: '🌍', key: 'int_openworld', detail: 'Exploration · Sandbox · Adventure' }
];

/* ════════════════════════════
   CLIPS
════════════════════════════ */
const CLIPS = [
    { id: 'clip1', title: 'First Victory', platform: 'twitch', embedId: 'CLIP_ID_1', thumbnail: '' },
    { id: 'clip2', title: 'Epic Boss Fight', platform: 'twitch', embedId: 'CLIP_ID_2', thumbnail: '' },
    { id: 'clip3', title: 'Funny Moment', platform: 'youtube', embedId: 'VIDEO_ID_1', thumbnail: '' },
];

