/* ============================================================
   ARUTA.SH — CONFIG
   Modifica questo file per aggiornare contenuti, social e testi.
   ============================================================ */

/* ════════════════════════════
   TRANSLATIONS
════════════════════════════ */
const i18n = {
    it: {
        char_class: 'Streamer · Programmatore · Avventuriero',
        sec_home:   'Home',
        sec_about:  'About',
        sec_live:   'Live',
        sec_links:  'Link',
        live_title: 'Reame Live',
        live_desc: 'Osserva il mago in azione attraverso il portale',
        live_offline: 'Il mago non \u00e8 nel reame... segui per essere avvisato del prossimo rituale.',
        links_desc: 'Trovami su queste piattaforme',
        bio: 'Mi chiamo Stefano Aruta. Programmatore appassionato con un amore profondo per anime, manga, Ultima Online, Minecraft e D&D. Come i protagonisti delle storie isekai, mi lancio ora in un nuovo viaggio: lo streaming. Cercando mondi senza confini dove libertà e creatività non hanno limite.',
        boot: [
            '✦ Un\'anima si risveglia in questo reame...',
            '⊕ Consultando il Tomo Antico...',
            '⋆ I Quattro Elementi rispondono...',
            '✦ Il cerchio magico prende forma...',
            '⊕ Il portale si apre...',
            '✦ Benvenuto nel Reame di Aruta ✦'
        ],
        int_gaming:    'Gaming',
        int_anime:     'Anime & Manga',
        int_coding:    'Programmazione',
        int_streaming: 'Streaming',
        int_fantasy:   'Fantasy & GdR',
        int_openworld: 'Open World',
        projects_title: 'Progetti in Corso',
        proj_stars: 'stelle',
        proj_forks: 'fork',
        proj_commits: 'commit',
        proj_issues: 'issue',
        proj_created: 'Creato',
        proj_updated: 'Aggiornato',
        proj_loading: 'Consultando gli archivi...',
        proj_error: 'Pergamena non trovata',
        live_schedule_title: '✦ Prossimi Rituali ✦',
        live_day_tue: 'Martedì',
        live_day_thu: 'Giovedì',
        live_day_sat: 'Sabato',
        live_countdown: 'Prossimo rituale tra',
        discord_title: 'Gilda Arcana',
        clips_title: 'Momenti Epici',
        sec_settings: 'Impostazioni',
        settings_appearance: 'Aspetto',
        settings_theme: 'Tema',
        settings_theme_desc: 'Passa dalla modalità chiara a quella scura',
        settings_fontsize: 'Dimensione testo',
        settings_fontsize_desc: 'Regola la dimensione del testo',
        settings_accent: 'Colore accento',
        settings_accent_desc: 'Scegli il colore principale',
        settings_clock: 'Orologio',
        settings_showdate: 'Mostra data',
        settings_showdate_desc: 'Mostra la data nella barra',
        settings_24h: 'Formato 24h',
        settings_24h_desc: 'Usa il formato a 24 ore',
        settings_sound: 'Suono',
        settings_ambient: 'Suono ambientale',
        settings_ambient_desc: 'Drone mistico di sottofondo',
        settings_language: 'Lingua',
        settings_lang: 'Lingua',
        settings_lang_desc: 'Seleziona la tua lingua',
        settings_about: 'Informazioni',
        settings_reset: 'Ripristina predefiniti',
        settings_reset_desc: 'Reimposta tutte le impostazioni ai valori predefiniti',
        start_share: 'Condividi'
    },
    en: {
        char_class: 'Streamer · Programmer · Adventurer',
        sec_home:   'Home',
        sec_about:  'About',
        sec_live:   'Live',
        sec_links:  'Links',
        live_title: 'Live Realm',
        live_desc: 'Watch the mage in action through the portal',
        live_offline: 'The mage is not in the realm... follow to be notified of the next ritual.',
        links_desc: 'Find me on these platforms',
        bio: 'My name is Stefano Aruta. A passionate programmer with a deep love for anime, manga, Ultima Online, Minecraft and D&D. Like the heroes of isekai tales, I now embark on a new journey: streaming. Seeking worlds without boundaries, where freedom and creativity know no limits.',
        boot: [
            '✦ A soul awakens in this realm...',
            '⊕ Consulting the Ancient Tome...',
            '⋆ The Four Elements respond...',
            '✦ The magic circle takes shape...',
            '⊕ The portal opens...',
            '✦ Welcome to the Realm of Aruta ✦'
        ],
        int_gaming:    'Gaming',
        int_anime:     'Anime & Manga',
        int_coding:    'Programming',
        int_streaming: 'Streaming',
        int_fantasy:   'Fantasy & RPG',
        int_openworld: 'Open World',
        projects_title: 'Current Projects',
        proj_stars: 'stars',
        proj_forks: 'forks',
        proj_commits: 'commits',
        proj_issues: 'issues',
        proj_created: 'Created',
        proj_updated: 'Updated',
        proj_loading: 'Consulting the archives...',
        proj_error: 'Scroll not found',
        live_schedule_title: '✦ Upcoming Rituals ✦',
        live_day_tue: 'Tuesday',
        live_day_thu: 'Thursday',
        live_day_sat: 'Saturday',
        live_countdown: 'Next ritual in',
        discord_title: 'Arcane Guild',
        clips_title: 'Epic Moments',
        sec_settings: 'Settings',
        settings_appearance: 'Appearance',
        settings_theme: 'Theme',
        settings_theme_desc: 'Switch between dark and light mode',
        settings_fontsize: 'Font Size',
        settings_fontsize_desc: 'Adjust text size',
        settings_accent: 'Accent Color',
        settings_accent_desc: 'Choose your accent color',
        settings_clock: 'Clock',
        settings_showdate: 'Show Date',
        settings_showdate_desc: 'Display date in taskbar',
        settings_24h: '24h Format',
        settings_24h_desc: 'Use 24-hour time format',
        settings_sound: 'Sound',
        settings_ambient: 'Ambient Sound',
        settings_ambient_desc: 'Mystical background drone',
        settings_language: 'Language',
        settings_lang: 'Language',
        settings_lang_desc: 'Select your language',
        settings_about: 'About',
        settings_reset: 'Reset to Defaults',
        settings_reset_desc: 'Reset all settings to default values',
        start_share: 'Share'
    },
    es: {
        char_class: 'Streamer · Programador · Aventurero',
        sec_home:   'Inicio',
        sec_about:  'Sobre mí',
        sec_live:   'En Vivo',
        sec_links:  'Enlaces',
        live_title: 'Reame en Vivo',
        live_desc: 'Observa al mago en acción a través del portal',
        live_offline: 'El mago no est\u00e1 en el reino... s\u00edguelo para ser notificado del pr\u00f3ximo ritual.',
        links_desc: 'Encuéntrame en estas plataformas',
        bio: 'Me llamo Stefano Aruta. Programador apasionado con un profundo amor por el anime, manga, Ultima Online, Minecraft y D&D. Como los protagonistas de las historias isekai, me lanzo ahora a un nuevo viaje: el streaming. Buscando mundos sin límites donde la libertad y la creatividad no tienen fronteras.',
        boot: [
            '✦ Un alma despierta en este reino...',
            '⊕ Consultando el Tomo Antiguo...',
            '⋆ Los Cuatro Elementos responden...',
            '✦ El círculo mágico toma forma...',
            '⊕ El portal se abre...',
            '✦ Bienvenido al Reino de Aruta ✦'
        ],
        int_gaming:    'Gaming',
        int_anime:     'Anime y Manga',
        int_coding:    'Programación',
        int_streaming: 'Streaming',
        int_fantasy:   'Fantasía y RPG',
        int_openworld: 'Mundo Abierto',
        projects_title: 'Proyectos Actuales',
        proj_stars: 'estrellas',
        proj_forks: 'forks',
        proj_commits: 'commits',
        proj_issues: 'issues',
        proj_created: 'Creado',
        proj_updated: 'Actualizado',
        proj_loading: 'Consultando los archivos...',
        proj_error: 'Pergamino no encontrado',
        live_schedule_title: '✦ Próximos Rituales ✦',
        live_day_tue: 'Martes',
        live_day_thu: 'Jueves',
        live_day_sat: 'Sábado',
        live_countdown: 'Próximo ritual en',
        discord_title: 'Gremio Arcano',
        clips_title: 'Momentos Épicos',
        sec_settings: 'Configuración',
        settings_appearance: 'Apariencia',
        settings_theme: 'Tema',
        settings_theme_desc: 'Cambiar entre modo claro y oscuro',
        settings_fontsize: 'Tamaño de fuente',
        settings_fontsize_desc: 'Ajustar el tamaño del texto',
        settings_accent: 'Color de acento',
        settings_accent_desc: 'Elige tu color de acento',
        settings_clock: 'Reloj',
        settings_showdate: 'Mostrar fecha',
        settings_showdate_desc: 'Mostrar la fecha en la barra',
        settings_24h: 'Formato 24h',
        settings_24h_desc: 'Usar formato de 24 horas',
        settings_sound: 'Sonido',
        settings_ambient: 'Sonido ambiental',
        settings_ambient_desc: 'Drone místico de fondo',
        settings_language: 'Idioma',
        settings_lang: 'Idioma',
        settings_lang_desc: 'Selecciona tu idioma',
        settings_about: 'Acerca de',
        settings_reset: 'Restablecer predeterminados',
        settings_reset_desc: 'Restablecer toda la configuración',
        start_share: 'Compartir'
    },
    ja: {
        char_class: 'ストリーマー · プログラマー · 冒険者',
        sec_home:   'ホーム',
        sec_about:  'について',
        sec_live:   'ライブ',
        sec_links:  'リンク',
        live_title: 'ライブ王国',
        live_desc: 'ポータルを通じて魔法使いの活動を見よう',
        live_offline: '魔法使いは王国にいません... 次の儀式の通知を受け取るにはフォローしてください。',
        links_desc: 'これらのプラットフォームで見つけてください',
        bio: '私はStefano Arutaです。アニメ、マンガ、ウルティマオンライン、マインクラフト、D&Dへの深い愛を持つ情熱的なプログラマーです。異世界転生の主人公のように、今私は新たな旅へ踏み出します——ストリーミングの世界へ。自由と創造性に限界のない世界を求めて。',
        boot: [
            '✦ この王国に魂が目覚める...',
            '⊕ 古代の書を開く...',
            '⋆ 四つの元素が応答する...',
            '✦ 魔法陣が形を成す...',
            '⊕ 転移門が開く...',
            '✦ アルタの王国へようこそ ✦'
        ],
        int_gaming:    'ゲーム',
        int_anime:     'アニメ & マンガ',
        int_coding:    'プログラミング',
        int_streaming: 'ストリーミング',
        int_fantasy:   'ファンタジー & RPG',
        int_openworld: 'オープンワールド',
        projects_title: '進行中のプロジェクト',
        proj_stars: 'スター',
        proj_forks: 'フォーク',
        proj_commits: 'コミット',
        proj_issues: 'イシュー',
        proj_created: '作成日',
        proj_updated: '更新日',
        proj_loading: '古文書を調べています...',
        proj_error: '巻物が見つかりません',
        live_schedule_title: '✦ 次の儀式 ✦',
        live_day_tue: '火曜日',
        live_day_thu: '木曜日',
        live_day_sat: '土曜日',
        live_countdown: '次の儀式まで',
        discord_title: '秘術のギルド',
        clips_title: '名場面',
        sec_settings: '設定',
        settings_appearance: '外観',
        settings_theme: 'テーマ',
        settings_theme_desc: 'ダーク/ライトモードの切替',
        settings_fontsize: 'フォントサイズ',
        settings_fontsize_desc: 'テキストサイズの調整',
        settings_accent: 'アクセントカラー',
        settings_accent_desc: 'メインカラーの選択',
        settings_clock: '時計',
        settings_showdate: '日付表示',
        settings_showdate_desc: 'バーに日付を表示',
        settings_24h: '24時間形式',
        settings_24h_desc: '24時間表示を使用',
        settings_sound: 'サウンド',
        settings_ambient: '環境音',
        settings_ambient_desc: '神秘的な背景ドローン',
        settings_language: '言語',
        settings_lang: '言語',
        settings_lang_desc: '言語を選択',
        settings_about: '情報',
        settings_reset: 'デフォルトに戻す',
        settings_reset_desc: 'すべての設定をリセット',
        start_share: '共有'
    },
    fn: {
        char_class: 'ᛊᛏᚱᛖᚨᛗᛖᚱ · ᛈᚱᛟᚷᚱᚨᛗᛗᛖᚱ · ᚨᛞᚹᛖᚾᛏᚢᚱᛖᚱ',
        sec_home:   'ᚺᛟᛗᛖ',
        sec_about:  'ᚨᛒᛟᚢᛏ',
        sec_live:   'ᛚᛁᚹᛖ',
        sec_links:  'ᛚᛁᚾᚲᛊ',
        live_title: 'ᛚᛁᚹᛖ ᚱᛖᚨᛚᛗ',
        live_desc: 'ᚹᚨᛏᚲᚺ ᚦᛖ ᛗᚨᚷᛖ ᛁᚾ ᚨᚲᛏᛁᛟᚾ',
        live_offline: 'ᚦᛖ ᛗᚨᚷᛖ ᛁᛊ ᚾᛟᛏ ᛁᚾ ᚦᛖ ᚱᛖᚨᛚᛗ...',
        links_desc: 'ᚠᛁᚾᛞ ᛗᛖ ᛟᚾ ᚦᛖᛊᛖ ᛈᛚᚨᛏᚠᛟᚱᛗᛊ',
        bio: 'ᛁ ᚨᛗ ᛊᛏᛖᚠᚨᚾᛟ ᚨᚱᚢᛏᚨ · ᚨ ᛈᚨᛊᛊᛁᛟᚾᚨᛏᛖ ᛈᚱᛟᚷᚱᚨᛗᛗᛖᚱ ᚹᛁᛏᚺ ᚨ ᛞᛖᛖᛈ ᛚᛟᚹᛖ ᚠᛟᚱ ᚨᚾᛁᛗᛖ · ᛗᚨᚾᚷᚨ · ᚢᛚᛏᛁᛗᚨ ᛟᚾᛚᛁᚾᛖ · ᛗᛁᚾᛖᚲᚱᚨᚠᛏ ᚨᚾᛞ ᛞᚨᚾᛞ · ᛚᛁᚲᛖ ᚦᛖ ᚺᛖᚱᛟᛖᛊ ᛟᚠ ᛁᛊᛖᚲᚨᛁ ᛏᚨᛚᛖᛊ · ᛁ ᚾᛟᚹ ᛖᛗᛒᚨᚱᚲ ᛟᚾ ᚨ ᚾᛖᚹ ᛃᛟᚢᚱᚾᛖᛃ · ᛊᛏᚱᛖᚨᛗᛁᚾᚷ · ᛊᛖᛖᚲᛁᚾᚷ ᚹᛟᚱᛚᛞᛊ ᚹᛁᛏᚺᛟᚢᛏ ᛒᛟᚢᚾᛞᚨᚱᛁᛖᛊ',
        boot: [
            '✦ ᚨ ᛊᛟᚢᛚ ᚨᚹᚨᚲᛖᚾᛊ ᛁᚾ ᚦᛁᛊ ᚱᛖᚨᛚᛗ...',
            '⊕ ᚲᛟᚾᛊᚢᛚᛏᛁᚾᚷ ᚦᛖ ᚨᚾᚲᛁᛖᚾᛏ ᛏᛟᛗᛖ...',
            '⋆ ᚦᛖ ᚠᛟᚢᚱ ᛖᛚᛖᛗᛖᚾᛏᛊ ᚱᛖᛊᛈᛟᚾᛞ...',
            '✦ ᚦᛖ ᛗᚨᚷᛁᚲ ᚲᛁᚱᚲᛚᛖ ᛏᚨᚲᛖᛊ ᛊᚺᚨᛈᛖ...',
            '⊕ ᚦᛖ ᛈᛟᚱᛏᚨᛚ ᛟᛈᛖᚾᛊ...',
            '✦ ᚹᛖᛚᚲᛟᛗᛖ ᛏᛟ ᚦᛖ ᚱᛖᚨᛚᛗ ᛟᚠ ᚨᚱᚢᛏᚨ ✦'
        ],
        int_gaming:    'ᚷᚨᛗᛁᚾᚷ',
        int_anime:     'ᚨᚾᛁᛗᛖ & ᛗᚨᚾᚷᚨ',
        int_coding:    'ᛈᚱᛟᚷᚱᚨᛗᛗᛁᚾᚷ',
        int_streaming: 'ᛊᛏᚱᛖᚨᛗᛁᚾᚷ',
        int_fantasy:   'ᚠᚨᚾᛏᚨᛊᛃ & ᚱᛈᚷ',
        int_openworld: 'ᛟᛈᛖᚾ ᚹᛟᚱᛚᛞ',
        projects_title: 'ᛈᚱᛟᛃᛖᚲᛏᛊ',
        proj_stars: 'ᛊᛏᚨᚱᛊ',
        proj_forks: 'ᚠᛟᚱᚲᛊ',
        proj_commits: 'ᚲᛟᛗᛗᛁᛏᛊ',
        proj_issues: 'ᛁᛊᛊᚢᛖᛊ',
        proj_created: 'ᚲᚱᛖᚨᛏᛖᛞ',
        proj_updated: 'ᚢᛈᛞᚨᛏᛖᛞ',
        proj_loading: 'ᚲᛟᚾᛊᚢᛚᛏᛁᚾᚷ...',
        proj_error: 'ᛊᚲᚱᛟᛚᛚ ᚾᛟᛏ ᚠᛟᚢᚾᛞ',
        live_schedule_title: '✦ ᚢᛈᚲᛟᛗᛁᚾᚷ ᚱᛁᛏᚢᚨᛚᛊ ✦',
        live_day_tue: 'ᛏᚢᛖᛊᛞᚨᛃ',
        live_day_thu: 'ᚦᚢᚱᛊᛞᚨᛃ',
        live_day_sat: 'ᛊᚨᛏᚢᚱᛞᚨᛃ',
        live_countdown: 'ᚾᛖᚲᛊᛏ ᚱᛁᛏᚢᚨᛚ ᛁᚾ',
        discord_title: 'ᚨᚱᚲᚨᚾᛖ ᚷᚢᛁᛚᛞ',
        clips_title: 'ᛖᛈᛁᚲ ᛗᛟᛗᛖᚾᛏᛊ',
        sec_settings: 'ᛊᛖᛏᛏᛁᚾᚷᛊ',
        settings_appearance: 'ᚨᛈᛈᛖᚨᚱᚨᚾᚲᛖ',
        settings_theme: 'ᚦᛖᛗᛖ',
        settings_theme_desc: 'ᛞᚨᚱᚲ / ᛚᛁᚷᚺᛏ',
        settings_fontsize: 'ᚠᛟᚾᛏ ᛊᛁᛉᛖ',
        settings_fontsize_desc: 'ᛏᛖᚲᛊᛏ ᛊᛁᛉᛖ',
        settings_accent: 'ᚨᚲᚲᛖᚾᛏ',
        settings_accent_desc: 'ᚲᛟᛚᛟᚱ',
        settings_clock: 'ᚲᛚᛟᚲᚲ',
        settings_showdate: 'ᛊᚺᛟᚹ ᛞᚨᛏᛖ',
        settings_showdate_desc: 'ᛞᚨᛏᛖ ᛁᚾ ᛒᚨᚱ',
        settings_24h: '24ᚺ',
        settings_24h_desc: '24ᚺ ᚠᛟᚱᛗᚨᛏ',
        settings_sound: 'ᛊᛟᚢᚾᛞ',
        settings_ambient: 'ᚨᛗᛒᛁᛖᚾᛏ',
        settings_ambient_desc: 'ᛞᚱᛟᚾᛖ',
        settings_language: 'ᛚᚨᚾᚷᚢᚨᚷᛖ',
        settings_lang: 'ᛚᚨᚾᚷ',
        settings_lang_desc: 'ᛊᛖᛚᛖᚲᛏ',
        settings_about: 'ᚨᛒᛟᚢᛏ',
        settings_reset: 'ᚱᛖᛊᛖᛏ',
        settings_reset_desc: 'ᛞᛖᚠᚨᚢᛚᛏᛊ',
        start_share: 'ᛊᚺᚨᚱᛖ'
    }
};

/* ════════════════════════════
   SOCIAL LINKS
════════════════════════════ */
const SOCIALS = [
    { id: 'twitch',    href: 'https://twitch.tv/aruta.sh',     platform: 'Twitch',      handle: 'aruta.sh',  icon: '<i class="fab fa-twitch link-card-icon"></i>' },
    { id: 'kick',      href: 'https://kick.com/aruta_sh',      platform: 'Kick',        handle: 'aruta_sh',  icon: '<svg class="link-card-icon" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M2 2h4v6l4-6h5l-5 7 5 7h-5l-4-6v6H2V2z"/></svg>' },
    { id: 'youtube',   href: 'https://youtube.com/@aruta.sh',  platform: 'YouTube',     handle: '@aruta.sh', icon: '<i class="fab fa-youtube link-card-icon"></i>' },
    { id: 'twitter',   href: 'https://twitter.com/aruta.sh',   platform: 'Twitter / X', handle: '@aruta.sh', icon: '<i class="fab fa-twitter link-card-icon"></i>' },
    { id: 'instagram', href: 'https://instagram.com/aruta_sr', platform: 'Instagram',   handle: 'aruta_sr',  icon: '<i class="fab fa-instagram link-card-icon"></i>' },
    { id: 'github',    href: 'https://github.com/Arutosio',    platform: 'GitHub',      handle: 'Arutosio',  icon: '<i class="fab fa-github link-card-icon"></i>' }
];

/* ════════════════════════════
   PROJECTS — just change the slug to swap a repo
════════════════════════════ */
const PROJECTS = [
    'Arutosio/Hina',
    'Arutosio/AnimeWorldDownloader'
];

/* ════════════════════════════
   INTERESTS
════════════════════════════ */
const INTERESTS = [
    { icon: '🎮', key: 'int_gaming',    detail: 'Ultima Online · Minecraft · D&D' },
    { icon: '🌸', key: 'int_anime',     detail: 'Isekai · Shonen · Seinen' },
    { icon: '💻', key: 'int_coding',    detail: 'Web · Scripts · Automation' },
    { icon: '📺', key: 'int_streaming', detail: 'Twitch · Kick · YouTube' },
    { icon: '⚔️', key: 'int_fantasy',   detail: 'Dungeons & Dragons · Roleplay' },
    { icon: '🌍', key: 'int_openworld', detail: 'Exploration · Sandbox · Adventure' }
];

/* ════════════════════════════
   CLIPS
════════════════════════════ */
const CLIPS = [
    { id: 'clip1', title: 'First Victory', platform: 'twitch', embedId: 'CLIP_ID_1', thumbnail: '' },
    { id: 'clip2', title: 'Epic Boss Fight', platform: 'twitch', embedId: 'CLIP_ID_2', thumbnail: '' },
    { id: 'clip3', title: 'Funny Moment', platform: 'youtube', embedId: 'VIDEO_ID_1', thumbnail: '' },
];

